name: Build APK con Buildozer

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Configurar JDK 17 (Requerido para Android SDK moderno)
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Compilar APK usando Buildozer Action
      uses: ArtemSBulgakov/buildozer-action@v3
      with:
        buildozer_version: stable
        # Esto forzará el log detallado directamente en la consola del Action
        command: buildozer -v android debug

    - name: Subir el APK generado como Artefacto
      uses: actions/upload-artifact@v4
      with:
        name: App-Colegio-Dante-APK
        path: bin/*.apk
